defmodule Uitstalling.Decks.Agent.Fake do
  @moduledoc """
  Deterministic test agent. Slide edits prefix the slide's main text field
  with the request prompt; deck creation returns a small fixed deck titled
  after the prompt. Prompts starting with "FAIL:" return invalid JSON to
  exercise the validate-retry-fail path.
  """

  @behaviour Uitstalling.Decks.Agent

  @impl true
  def generate_slide(deck, request, _errors) do
    if String.starts_with?(request["prompt"], "FAIL:") do
      {:ok, %{"layout" => "hero_banner", "html" => "<h1>nope</h1>"}}
    else
      edit_slide(deck, request)
    end
  end

  @impl true
  def generate_deck(request, _errors) do
    if String.starts_with?(request["prompt"], "FAIL:") do
      {:ok, %{"title" => "bad", "slides" => [%{"layout" => "hero_banner"}]}}
    else
      {:ok,
       %{
         "title" => "FAKE DECK: #{request["prompt"]}",
         "slides" => [
           %{
             "id" => "s0",
             "layout" => "title",
             "heading" => "FAKE DECK: #{request["prompt"]}",
             "subheading" => "#{request["minutes"]} minutes, #{request["target_slides"]} slides"
           },
           %{"id" => "s1", "layout" => "statement", "body" => "Generated by the fake agent."}
         ]
       }}
    end
  end

  defp edit_slide(deck, request) do
    slide =
      Enum.find(deck["slides"], &(&1["id"] == request["slide_id"])) ||
        Enum.at(deck["slides"], request["slide_index"])

    key =
      cond do
        Map.has_key?(slide, "heading") -> "heading"
        Map.has_key?(slide, "body") -> "body"
        true -> "kicker"
      end

    {:ok, Map.put(slide, key, "AGENT: #{request["prompt"]}")}
  end
end
